CREATE DATABASE LibraryManagement
USE LibraryManagement;

CREATE TABLE Users (
UserId INT PRIMARY KEY IDENTITY(100,1),
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(80) UNIQUE NOT NULL,
PhoneNo VARCHAR(10)UNIQUE NOT NULL,
Password VARCHAR(50) NOT NULL)

ALTER TABLE Users
ADD CONSTRAINT UniqueUserRow
UNIQUE (FirstName , LastName , Email , PhoneNo )

CREATE TABLE Author(
AuthId INT PRIMARY KEY IDENTITY(100,1),
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL)

ALTER TABLE Author
ADD Email VARCHAR(50) UNIQUE NOT NULL

ALTER TABLE Author
ADD CONSTRAINT UniqueAuthorRow
UNIQUE(FirstName , LastName , Email)

CREATE TABLE Publisher (
PubId INT PRIMARY KEY IDENTITY(100,1),
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(80) UNIQUE NOT NULL)

ALTER TABLE Publish
ADD CONSTRAINT Unique_BookId
UNIQUE (BookId)

ALTER TABLE Publisher
ADD CONSTRAINT UniquePublisherRow
UNIQUE (FirstName , LastName , Email)

CREATE TABLE Genre(
GenreId INT PRIMARY KEY IDENTITY(100,1),
Title VARCHAR(50) UNIQUE NOT NULL)

CREATE TABLE Librarian(
LibId INT PRIMARY KEY IDENTITY(100,1),
FirstName VARCHAr(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(80) UNIQUE NOT NULL)

ALTER TABLE Librarian
ADD CONSTRAINT UniqueLibrarianRow
UNIQUE (FirstName , LastName , Email)

CREATE TABLE Book (
BookId INT PRIMARY KEY IDENTITY(100,1),
Title VARCHAR(50) NOT NULL,
Price INT NOT NULL,
AuthId INT FOREIGN KEY REFERENCES Author(AuthId),
GenreId INT FOREIGN KEY REFERENCES Genre(GenreId)) 

ALTER TABLE Book
ADD CONSTRAINT UniqueBookRow
UNIQUE (Title , GenreId )

CREATE TABLE Fine(
FineId INT PRIMARY KEY IDENTITY(100,1),
Amount INT,
UserId INT FOREIGN KEY REFERENCES Users(UserId))

CREATE TABLE Publish(
PublishId INT PRIMARY KEY IDENTITY (100,1),
PubId INT FOREIGN KEY REFERENCES Publisher(PubId),
BookId INT FOREIGN KEY REFERENCES Book(BookId),
PublishYear INT NOT NULL
CONSTRAINT CheckYear
CHECK (LEN(PublishYear) = 4)) 

ALTER TABLE Publish
ADD CONSTRAINT UniquePublishRow
UNIQUE (PubId , BookId )

CREATE TABLE Registration(
RegId INT PRIMARY KEY IDENTITY(100,1),
RegDate DATE NOT NULL,
PubId INT FOREIGN KEY REFERENCES Publisher(PubId),
BookId INT FOREIGN KEY REFERENCES Book(Bookid),
AuthId INT FOREIGN KEY REFERENCES Author(AuthId),
LibId INT FOREIGN KEY REFERENCES Librarian(LibId))

ALTER TABLE Registration
ADD CONSTRAINT UniqueRegistrationRow
UNIQUE (PubId , AuthId , BookId )

CREATE TABLE Issue(
IssueId INT PRIMARY KEY IDENTITY(1001,1),
LibId INT FOREIGN KEY REFERENCES Librarian(LibId),
UserId INT FOREIGN KEY REFERENCES Users(UserId),
BookId INT FOREIGN KEY REFERENCES Book(BookId),
IssueDate DATE NOT NULL,
ReturnDate DATE NOT NULL)


ALTER TABLE Book
ADD PublishDate DATE NOT NULL DEFAULT '2010-10-20'

select * from Book
select * from Publish


ALTER TABLE Publish
ADD PublishYear INT NOT NULL
CONSTRAINT CheckYear
CHECK (LEN(PublishYear) = 4 AND PublishYear > 1800 AND PublishYear < 2100 )

